version: '3.8'

services:
  kong:
    image: kong:latest
    container_name: kong-gateway
    user: "root"
    environment:
      KONG_DATABASE: "off" # Modo sin base de datos (más ligero)
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - .:/usr/local/kong/declarative # Monta tu carpeta actual dentro del contenedor
    ports:
      - "8000:8000" # Puerto para las peticiones de React
      - "8001:8001" # Puerto para administrar Kong
    restart: always